### ISSUE TITLE
spirit2dm1 is missing

### ISSUE THREAD

**Issue by andwj** [dfsp-spirit/spirit-quake-maps-gpl#2]
spirit2dm1 is absent, please add it to this repository.

BTW, thanks for releasing the source of your maps.

**Comment by dfsp-spirit** [comment]
Oh, thanks ofr the info. Will do.

I'll be very busy for the next 2 weeks for personal reasons, so give me some time, but I'll add it.

In the meantime, you can get the map file from this archive: http://maps.rcmd.org/quake2/spirit2dm1/spirit2dm1.zip

Best,

Tim

**Comment by dfsp-spirit** [comment]
I have added spirit2dm1, so I am closing this.
